variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent-Maven-job
  pool:
    name: vmdevopsagentsbs
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Maven@4
    displayName: Maven pom.xml
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
      publishJUnitResults: false
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.war'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
...
