# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# To avoid executing Task:Docker-BuildNPush, comment that Task only and hardCode the Tag variable with value from ACR.
# Additionally imagePullSecret is not required as KubernetesServiceConnection has been added in Devops->ProjSetings->ServiceConnection

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b8e9e0b3-d004-46c9-a308-9f78acb7434d'
  imageRepository: 'image-sprbootjavatomcat'
  containerRegistry: 'containerregistrysbssouth-g3fjc2dmh6g7ctgb.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  #imagePullSecret: 'containerregistrysbssouth1543419d-auth'

  # Agent VM image name
pool:
  name: 'vmdevopsagentsbs'


stages:
- stage: Build
  displayName: Build and push Docker image to ACR
  jobs:
  - job: Build
    displayName: Build and push Docker image to ACR   
    steps:
    - task: Docker@2
      displayName: Build and push Docker image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to Aks
  dependsOn: Build

  jobs:
  - job: deploy
    displayName: Download Artifacts and Deploy to AKS
    steps:
    #- task: KubernetesManifest@1
    #  displayName: Create imagePullSecret
    #  inputs:
    #    action: createSecret
    #    kubernetesServiceConnection: 'kubernetes-service-connection'
    #    secretName: $(imagePullSecret)
    #    dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(Build.ArtifactStagingDirectory)'

    - task: KubernetesManifest@1
      inputs:
        action: deploy
        kubernetesServiceConnection: 'kubernetes-service-connection'
        namespace: default
        manifests: |
          $(Build.ArtifactStagingDirectory)/kubernetes/deployment.yaml
          $(Build.ArtifactStagingDirectory)/kubernetes/service.yaml              
        containers: |
          $(containerRegistry)/$(imageRepository):$(tag)
