# --- STAGE 1: Copy WAR from Host to Container---

# Start from Eclipse Temurin JRE 21 on Ubuntu Jammy
# Image available from Url: https://hub.docker.com/_/eclipse-temurin/tags?name=21-jre-jammy
# 'appsource' is the name of the copy stage, which we will reference in the second stage
FROM eclipse-temurin:21-jre-jammy AS appsource

# Set the working directory inside the container
WORKDIR /myapp

# Copy your application files from your host's build context (where your Dockerfile is) 
# into the /app directory inside the container
COPY . .

# List the contents of the /myapp directory to verify the files are copied correctly
# However the the contents of the /myapp directory are not listed during docker build in local host machine as the build context does not include the target directory, which is generated after running mvn package locally.
RUN ls -la /myapp/


# STAGE 2: Deploy the WAR file to a Tomcat container
# Ensure the Tomcat version supports the JDK version used for building
# Image Avlble in URL: https://hub.docker.com/_/tomcat/tags?name=10.1.24-jdk21-temurin-jammy
FROM tomcat:10.1.24-jdk21-temurin-jammy

# Remove default web applications (optional, adjust as needed for your deployment)
RUN rm -rf /usr/local/tomcat/webapps/*

# Set the JAVA_OPTS environment variable to pass JVM arguments
# Tomcat's catalina.sh script automatically picks up the JAVA_OPTS and CATALINA_OPTS variables
ENV JAVA_OPTS="-Dspring.profiles.active=prod"

# Set the working directory in the container
WORKDIR /usr/local/tomcat/webapps/

# Copy the WAR file from the 'build' stage to the Tomcat webapps directory
COPY --from=appsource /myapp/target/*.war bootghcp.war 

# Expose the container to run on this port
EXPOSE 8080

# The default CMD of the tomcat image runs catalina.sh, which starts the server
CMD ["catalina.sh", "run"]