spring.application.name=bootghcp
server.port=8080
## Either of below properties can be used to set the context path for the application, both are equivalent
## server.servlet.contextPath=/bootghcp
server.servlet.context-path=/bootghcp


# To create a H2 persistent Db create an empty file as: database/testghcp.mv.db
## spring.datasource.url=jdbc:h2:file:./src/main/resources/database/testghcp;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.url=jdbc:h2:file:opt/myapp/db/testghcp
## Keeping the Db in resources folder as below, gives error as file not found.
## spring.datasource.url=jdbc:h2:classpath:database/testghcp

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Schema Initialization Mode
# H2 does not require a DatabaseSchema to be created, only requires the Table schemas.
# Below Sql files have to exactly have those names as H2 autoconfiguration is hardcoded to read those name files only 
# The files have to be directly placed in 'resources' folder
# Initially set Mode to 'always' to run schema.sql and data.sql scripts on startup from resources classpath
# Once Db file is persisted set to 'never' to avoid re-running the Sql scripts
## spring.sql.init.mode=always
spring.sql.init.mode=never

# METHOD 1: Use SQL scripts (schema.sql/data.sql) - Recommended for initialization
# Disable Jpa-Hibernate's automatic DDL generation to avoid conflicts
spring.jpa.hibernate.ddl-auto=none 
# If you are using data.sql and schema.sql together, you might need to defer the initialization
# This property ensures the schema is created before data insertion scripts run
spring.jpa.defer-datasource-initialization=true

# METHOD 2: Use Hibernate to generate schema from Entities
# spring.jpa.hibernate.ddl-auto=update or create, create-drop

# H2 console enabled for development
## Url: http://localhost:8088/bootghcp/h2-console
## For H2 console use below properties:
### Saved Settings: Generic H2(Embedded
### Username: sa; Password: (leave blank)
### Jdbc URL: jdbc:h2:file:C:/Savitha/Projects/SERVERS/Database/H2/testghcp
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true

