-- Insert sample records into USERDETAILS
INSERT INTO USERDETAILS (FIRSTNAME, LASTNAME, EMAILID, CREATEDON, UPDATEDON)
VALUES ('Alice', 'Smith', 'alice.smith@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO USERDETAILS (FIRSTNAME, LASTNAME, EMAILID, CREATEDON, UPDATEDON)
VALUES ('Bob', 'Johnson', 'bob.johnson@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
