-- Create userdetails table in TESTGHCP schema
CREATE TABLE IF NOT EXISTS USERDETAILS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAILID VARCHAR(255) NOT NULL UNIQUE,
    CREATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Optional: create an index on email
--CREATE UNIQUE INDEX IF NOT EXISTS IDX_USERDETAILS_EMAIL ON USERDETAILS(EMAILID);
